(require 'base-completion)

(define-completion czech-complete-e^ "e^" (insert "ě") t)
(define-completion czech-complete-s^ "s^" (insert "š") t)
(define-completion czech-complete-c^ "c^" (insert "č") t)
(define-completion czech-complete-r^ "r^" (insert "ř") t)
(define-completion czech-complete-z^ "z^" (insert "ž") t)
(define-completion czech-complete-n^ "n^" (insert "ň") t)
(define-completion czech-complete-y` "y`" (insert "ý") t)
(define-completion czech-complete-a` "a`" (insert "á") t)
(define-completion czech-complete-i` "i`" (insert "í") t)
(define-completion czech-complete-o` "o`" (insert "o") t)
(define-completion czech-complete-e` "e`" (insert "é") t)
(define-completion czech-complete-u^ "u^" (insert "ů") t)
(define-completion czech-complete-u` "u`" (insert "ú") t)

(provide-me)
